apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "funkwhale.fullname" . }}-beat
  labels:
    {{- include "funkwhale.labels" . | nindent 4 }}
    audio.funkwhale/component: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "funkwhale.selectorLabels" . | nindent 6 }}
      audio.funkwhale/component: celery-beat
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "funkwhale.selectorLabels" . | nindent 8 }}
        audio.funkwhale/component: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: {{ include "funkwhale.imageUri" (dict "Scope" .Values.celery.image "Values" .Values "Chart" .Chart) | quote }}
          imagePullPolicy: {{ .Values.celery.image.pullPolicy | default .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - funkwhale_api.taskapp
            - beat
            - -l
            - {{ .Values.celery.beat.logLevel | default "info" | upper }}
          env:
            {{ include "funkwhale.envVars" . | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ include "funkwhale.fullname" . }}
          - secretRef:
              name: {{ include "funkwhale.fullname" . }}
          {{- with .Values.extraEnvFrom }}
            {{ . | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.celery.beat.resources | nindent 12 }}
      {{- with .Values.celery.beat.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.celery.beat.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.celery.beat.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
