{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "funkwhale.fullname" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "funkwhale.fullname" . }}
  labels:
    {{- include "funkwhale.labels" . | nindent 4 }}
data:
  {{ if $secret -}}
  DJANGO_SECRET_KEY: {{ (.Values.djangoSecret | default (b64dec $secret.data.DJANGO_SECRET_KEY)) | b64enc }}
  {{ else -}}
  DJANGO_SECRET_KEY: {{ (.Values.djangoSecret | default uuidv4) | b64enc }}
  {{ end -}}
  {{ if not .Values.redis.existingSecret -}}
  CACHE_URL: {{ include "funkwhale.redisUrl" . | b64enc }}
  {{ end -}}
  {{ if not .Values.postgresql.existingSecret -}}
  DATABASE_URL: {{ include "funkwhale.dbUrl" . | b64enc }}
  {{ end -}}
  {{ if and .Values.s3.enabled (not .Values.s3.existingSecret) -}}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretKey | b64enc }}
  {{ end -}}

{{- range $key, $val := .Values.extraSecret }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
