---
apiVersion: v2
name: matrix-synapse
description: Matrix reference homeserver
appVersion: 1.18.0

type: application
version: 0.1.0
maintainers:
  - name: Alexander Olofsson
    email: ace@haxalot.com

dependencies:
  - name: postgresql
    version: ~8.9.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ~10.6.10
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
