{{- $insideArgoCD := (or .Values.argoCD (.Capabilities.APIVersions.Has "argoproj.io/v1alpha1")) }}
{{- $secretName := include "matrix-synapse.workername" (dict "global" . "worker" "signingkey") }}

{{- if .Values.signingkey.job.enabled }}
{{- if .Values.signingkey.existingSecret }}
{{- fail "Can't specify both signingkey.job.enabled and signingkey.existingSecret" }}
{{- end }}
{{- $name := include "matrix-synapse.workername" (dict "global" . "worker" "signingkey-job") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: signingkey-job
  {{- if not $insideArgoCD }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: signingkey-job
  {{- if not $insideArgoCD }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - {{ $secretName }}
    verbs:
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: signingkey-job
  {{- if not $insideArgoCD }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: signingkey-job
  {{- if or .Values.signingkey.job.annotations (not $insideArgoCD) }}
  annotations:
    {{- if not $insideArgoCD }}
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    {{- end }}
  {{- with .Values.signingkey.job.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        {{- include "matrix-synapse.labels" . | nindent 8 }}
        app.kubernetes.io/component: signingkey-job
    spec:
      containers:
        - command:
            - sh
            - -c
            - |
              echo "Generating signing key..."
              if which generate_signing_key.py >/dev/null; then
                generate_signing_key.py -o /synapse/keys/signing.key
              else
                generate_signing_key -o /synapse/keys/signing.key
              fi
          image: "{{ .Values.signingkey.job.generateImage.repository }}:{{ .Values.signingkey.job.generateImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.signingkey.job.generateImage.pullPolicy }}
          name: signing-key-generate
          resources:
            {{- toYaml .Values.signingkey.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.signingkey.job.podSecurityContext | nindent 12 }}
          volumeMounts:
            - mountPath: /synapse/keys
              name: matrix-synapse-keys
        - command:
            - sh
            - -c
            - |
              printf "Checking rights to update secret... "
              kubectl auth can-i update secret/${SECRET_NAME}
              /scripts/signing-key.sh
          env:
            - name: SECRET_NAME
              value: {{ $secretName }}
          image: "{{ .Values.signingkey.job.publishImage.repository }}:{{ .Values.signingkey.job.publishImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.signingkey.job.publishImage.pullPolicy }}
          name: signing-key-upload
          resources:
            {{- toYaml .Values.signingkey.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.signingkey.job.podSecurityContext | nindent 12 }}
          volumeMounts:
            - mountPath: /scripts
              name: scripts
              readOnly: true
            - mountPath: /synapse/keys
              name: matrix-synapse-keys
              readOnly: true
      securityContext:
        {{- toYaml .Values.signingkey.job.securityContext | nindent 8 }}
      restartPolicy: Never
      serviceAccount: {{ $name }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "matrix-synapse.fullname" . }}-scripts
            defaultMode: 0755
        - name: matrix-synapse-keys
          emptyDir: {}
  parallelism: 1
  completions: 1
  backoffLimit: 1
{{- end }}
---
# Create secret if signing key job is enabled, or if we're running in ArgoCD and we don't have an existing secret
{{- if or .Values.signingkey.job.enabled (and (not .Values.signingkey.existingSecret) $insideArgoCD) }}
apiVersion: v1
kind: Secret
metadata:
  {{- if not $insideArgoCD }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: never
    helm.sh/resource-policy: keep
    # If for some reason we didn't detect ArgoCD, but are running in it, we want to make sure we don't delete the secret
    argocd.argoproj.io/hook: Skip
  {{- end }}
  name: {{ $secretName }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: signingkey-job
{{ $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
{{ if $secret -}}
data:
  signing.key: {{ (b64dec (index $secret.data "signing.key")) | b64enc }}
{{ end -}}
{{- end }}
